defaults:
  - _self_
  - logging: wandb
  - task: ???
  - alg: ???
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

experiment_name: gptj-lora
    #experiment_name: test

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
