defaults:
  - _self_
  - logging: wandb
  - task: ???
  - alg: ???
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

    #experiment_name: ppo_ref
    #experiment_name: mistral_supervised
    #experiment_name: ppo_ref_high_learning_with_warmup_decay_lag_with_mask
experiment_name: ppo_with_chosen
    #experiment_name: test

hydra:
  run:
    dir: outputs/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
