#!/bin/bash
#SBATCH -J PPOPP
#SBATCH -o /home/jdc396/slurm/logs/%j.out
#SBATCH -e /home/jdc396/slurm/logs/%j.err
#SBATCH --requeue
#SBATCH -N 1
#SBATCH -n 32
#SBATCH --mem=300G
#SBATCH -t 240:00:00
#SBATCH --partition=lancer
#SBATCH --gres=gpu:a6000:8
#SBATCH --nodelist=lancer-compute-01

source /home/jdc396/miniconda3/etc/profile.d/conda.sh
conda activate release_test
cd /home/jdc396/tril

./ppopp.sh
